services:
  # Define the application
  retrieval:
    # Build the Dockerfile that's in the RAG directory
    build: ./eAS
    # Define the directory in the service that connects to the shared volume 
    volumes:
      - vol-input-data:/app/volume
    # Expose necessary ports for API server
    ports:
      - '5050:5050'
    ##keep standard input open and assign a terminal for user queries (For Testing)
    #stdin_open: true
    #tty: true
  
  # Define datascraper
  scraper:
    build: ./DataScraper
    volumes:
      - vol-input-data:/app/volume

  # Define the database
  database:
    build: ./Database
    depends_on:
      - scraper
    volumes:
      - vol-input-data:/app/volume

# Define the shared volume  
volumes:
  vol-input-data: 
