services:
  # Define the application
  retrieval:
    # Build the Dockerfile that's in the RAG directory
    build: ./ecomAssistant
    # Define the directory in the service that connects to the shared volume 
    volumes:
      - vol-input-data:/app/volume
    # Expose necessary ports for API server
    ports:
      - '5050:5050'
    ##keep standard input open and assign a terminal for user queries (For Testing)
    #stdin_open: true
    #tty: true

  # Define the database: https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/ && https://www.linkedin.com/pulse/configuring-connecting-postgresql-database-docker-dqeze/
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5431:5432'

# Define the shared volume  
volumes:
  vol-input-data: 
  pgdata:
