services:
  # Define the application
  retrieval:
    # Build the Dockerfile that's in the RAG directory
    build: ./
    # Define the directory in the service that connects to the shared volume 
    volumes:
      - vol-input-data:/app/volume
    # Expose necessary ports for API server
    ports:
      - '127.0.0.1:5050:5050'
    depends_on:
      - db
      - populator

  # Define the database: https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/ && https://www.linkedin.com/pulse/configuring-connecting-postgresql-database-docker-dqeze/
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    # For local testing
    ports:
      - 127.0.0.1:5431:5432

  populator:
    build: ./db
    command: ["python", "/app/population/run_populator_scripts.py"]
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
      POSTGRES_DB: eassistant
    depends_on:
      - db

# Define the shared volume  
volumes:
  vol-input-data: 
  pgdata:
