version: '3'
services:
  # Define the hello application
  hello:
    
    # Build the Dockerfile that's in the hello directory
    build: ./hello

  # Define the goodbye application
  goodbye:
    
    # Build the Dockerfile that's in the goodbye directory
    build: ./goodbye

    # Don't create this container until the hello container (below) has been created
    depends_on:
      - hello

    # Expose port 5001 to the host machine
    ports:
    - "5001:5001"


