name: Run Bash Script on Push

on: [push]

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker container
        run: |
          docker build -t retriever:test eAS/.
          docker run retriever:test
